name: main-yml-for-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: git-wrkflow-action
      uses: actions/main@v1
      
    
